// <auto-generated/>
using PROFiLiX.Common.ApiClient;
using PROFiLiX.Common.Configuration;
using PROFiLiX.GUI.General;
using Microsoft.Win32;

namespace PROFiLiX.GUI.Forms
{
    public partial class FormSettings : Form
    {
        private Form FormMain;
        private bool firstLoad = true;

        GUIElements guiElements = new GUIElements();
        IAppConfig PROFiLiX = new AppConfig();

        public FormSettings(Form formMain)
        {
            InitializeComponent();
            this.FormMain = formMain;
        }

        private void btnExit_Click(object sender, EventArgs e)
        {
            PROFiLiX.Logger.LogAsync($"Closing settings screen");
            this.Close();
        }

        private void FormSettings_Load(object sender, EventArgs e)
        {
            this.Location = new Point(Screen.PrimaryScreen.WorkingArea.Width - this.Width, (Screen.PrimaryScreen.WorkingArea.Height - this.Height) - (this.FormMain.Height + 3));

            PROFiLiX.Logger.LogAsync($"Loading settings screen");
            switch (PROFiLiX.ClearTempAtStart)
            {
                case "Yes":
                    this.chkClearTempAtStart.Checked = true;
                    break;
                case "No":
                    this.chkClearTempAtStart.Checked = false;
                    break;
                default:
                    this.chkClearTempAtStart.Checked = false;
                    break;
            }
            firstLoad = false;
        }

        private async void Clicked(object sender, EventArgs e)
        {
            if (!firstLoad)
            {
                if (chkClearTempAtStart.Checked == true)
                {
                    PROFiLiX.Registry.SetRegistryValue("ClearTempAtStart", PROFiLiX.AppRegistryKey, "Yes", RegistryHive.CurrentUser);
                    await PROFiLiX.Logger.LogAsync($"Updated ClearTempAtStart: Yes");
                    this.lblStatus.Text = "Saved setting, ClearTempAtStart: Yes";

                }
                else
                {
                    PROFiLiX.Registry.SetRegistryValue("ClearTempAtStart", PROFiLiX.AppRegistryKey, "No", RegistryHive.CurrentUser);
                    await PROFiLiX.Logger.LogAsync($"Updated ClearTempAtStart: No");
                    this.lblStatus.Text = "Saved setting, ClearTempAtStart: No";
                }
            }
        }
    }
}
